### PR TITLE
Change extension name to Zicfisslp

### PR DESCRIPTION
**Pull request by ved-rivos**

### CODE REVIEW

**Comment by kacouane** [comment]
just a remark that the readme.md need to be updated as well

**Comment by ved-rivos** [comment]
> just a remark that the readme.adoc need to be updated as well

The TG name does not change. I did not find a reference to extension name in readme.adoc.

**Comment by kacouane** [comment]
Ok you are right

**Review by deepak0414 — APPROVED** [review]

**Comment by ved-rivos** [comment]
Updated the readme to make the expand the TG name.

**Pull request merged**
